config/routes.rb
NewApp::Application.routes.draw do
  resources :pages
  match '*pages/:title/edit' => 'pages#edit'
  match '*pages/:title/new' => 'pages#new'

end

app/models/page.rb
class Page < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  # GET /pages
  # GET /pages.json
  def md2(text)
    temp1=text.scan (/\\\\.+?\\\\/)
    temp1.each do |t1|
        t1=t1.gsub(/\A\\\\/, '<i>')
        t1=t1.gsub(/\\\\\z/, '</i>')
        text[/\\\\.+?\\\\/]=t1
    end
  text
  end
  def md3(text)
      temp1=text.scan (/\({2}.+?\){2}/)
        temp1.each do |t1|
        t1=t1.gsub(/\(\(/, '<a href="http://')
            t1[/\<a href\=.+?\s/]=t1[/\<a href\=.+?\s/]+'"> '
            t1=t1.gsub(/\)\)\z/, '</a>')
            puts t1
        text[/\({2}.+?\){2}/]=t1
    end
        text
  end
  def md1(text)
      temp=text.scan /\*{2}.+\*{2}/
    temp.each do |t|
           
          t=t.gsub(/\A\*{2}/, '<b>')
          t=t.gsub(/\*{2}\z/, '</b>')
          text[/\*{2}.+\*{2}/]=t
      end#\\{2}\w+?\\{2}
        text
  end
  def index
    @pages = Page.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pages }
    end
  end

  # GET /pages/1
  # GET /pages/1.json
  def show
    @page = Page.find_by_title(params[:id])
    @page.val=md3(md2(md1(@page.val))).html_safe

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/new
  # GET /pages/new.json
  def new
    @page = Page.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @page }
    end
  end

  # GET /pages/1/edit
  def edit
    #@post = Post.find_by_title(t)
    @page = Page.find_by_title(params[:id])
  end

  # POST /pages
  # POST /pages.json
  def create
    @page = Page.new(params[:page])
    @page.page_id=params[:id]

    respond_to do |format|
      if @page.save
        format.html { redirect_to 'pages/'+@page.title, notice: 'Page was successfully created.' }
        format.json { render json: @page, status: :created, location: @page }
      else
        format.html { render action: "new" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end

  end

  # PUT /pages/1
  # PUT /pages/1.json
  def update
    @page = Page.find_by_title(params[:page][:title])

    respond_to do |format|
      if @page.update_attributes(params[:page])
        format.html { redirect_to "/pages" }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pages/1
  # DELETE /pages/1.json
  def destroy
    @page = Page.find(params[:id])
    @page.destroy

    respond_to do |format|
      format.html { redirect_to pages_url }
      format.json { head :ok }
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/pages_helper.rb
module PagesHelper
	def md1(text)
    	temp=text.scan /\*{2}.+\*{2}/
		temp.each do |t|
           
        	t=t.gsub(/\A\*{2}/, '<b>')
        	t=t.gsub(/\*{2}\z/, '</b>')
        	text[/\*{2}.+\*{2}/]=t
    	end#\\{2}\w+?\\{2}
        text
	end

	def md2(text)
		temp1=text.scan (/\\\\.+?\\\\/)
		temp1.each do |t1|
    		t1=t1.gsub(/\A\\\\/, '<i>')
    		t1=t1.gsub(/\\\\\z/, '</i>')
    		text[/\\\\.+?\\\\/]=t1
		end
	text
	end
	def md3(text)
    	temp1=text.scan (/\({2}.+?\){2}/)
        temp1.each do |t1|
    		t1=t1.gsub(/\(\(/, '<a href="')
           	t1[/\<a href\=.+?\s/]=t1[/\<a href\=.+?\s/]+'> '
            t1=t1.gsub(/\)\)\z/, '</a>')
            puts t1
    		text[/\({2}.+?\){2}/]=t1
		end
        text
	end
end

app/views/pages/_form.html.erb
<%= form_for(@page) do |f| %>
  <% if @page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
      <% @page.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class'field'>
    <%=f.hidden_field :id%>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :val %><br />
    <%= f.text_area :val %>
  </div>
  
  <div class="actions">
    <%= f.submit "update" %>
  </div>
<% end %>

app/views/pages/edit.html.erb
<h1>Editing page</h1>

<%= render 'form' %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/index.html.erb
<h1>Listing pages</h1>

<table>
  <tr>
    <th>Title</th>
    <th>Val</th>
    <th>Page</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @pages.each do |page| %>
  <tr>
    <td><%= page.title %></td>
    <td><%= page.val %></td>
    <td><%= page.page_id %></td>
    
  </tr>
<% end %>
</table>

<br />

app/views/pages/new.html.erb
<h1>New page</h1>

<%= render 'form' %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Title:</b>
  
</p>

<p>
  <b>Val:</b>
  <%=@page.val %>
</p>

<p>
  <b>Page:</b>
  <%= @page.page_id %>
</p>



<%= link_to 'Back', pages_path %>